apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: primary-70-no-dsscripttest
  namespace: bu528-stop-wasting-the-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcg
  template:
    metadata:
      labels:
        app: wcg
    spec:
      nodeName: k008
      containers:
      - name: latest
        image: siddharthbakshi/wcg_centos
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "7"
            memory: "35Gi"
          limits:
            cpu: "7"
            memory: "35Gi"
        env:
        - name: boincurl
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boincurl
        - name: boinckey
          valueFrom:
            configMapKeyRef:
              name: boinc-url-key
              key: boinckey